### ISSUE TITLE
Users should not be able to set their own time zones.

### ISSUE THREAD

**Issue by thejimbirch** [kanopi/saplings-base#3]
On /admin/config/regional/settings
Uncheck Users may set their own time zone .

**Comment by thejimbirch** [comment]
```
system.date:
  simple_config_update:
    timezone.default: America/New_York
    user.configurable: false
```
